version: '3.8'
services:
  frontend:
    image: node:16
    container_name: vue-app
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    command: >
      sh -c "npm install -g yarn --force && yarn install && yarn serve"

  backend:
    image: gradle:8.10.0-jdk21
    container_name: kotlin-backend
    working_dir: /app
    volumes:
      - ./backend/csvgen:/app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    command: >
      sh -c "./gradlew bootRun"

  database:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: