spring:
  application:
    name: csvgen

  datasource:
    url: jdbc:postgresql://database:5432/mydb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Disable auto schema update when using Liquibase
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
server:
  port: 8081